// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA09T0yew9XFTbtU4ijqvO-1s67dYyLCrM',
    appId: '1:502778469026:web:ffd725ca0fd7a9426555fb',
    messagingSenderId: '502778469026',
    projectId: 'lilac-flutter-machine-test',
    authDomain: 'lilac-flutter-machine-test.firebaseapp.com',
    storageBucket: 'lilac-flutter-machine-test.appspot.com',
    measurementId: 'G-R41627FWP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjCPUHhPHU1sS7j44uE7tv5AcMs1TRK1o',
    appId: '1:502778469026:android:91ce8de0796ca4826555fb',
    messagingSenderId: '502778469026',
    projectId: 'lilac-flutter-machine-test',
    storageBucket: 'lilac-flutter-machine-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWH-U_QxGs8ZWqPhAB_O1b57LMJeCycDE',
    appId: '1:502778469026:ios:32791b52b9f38aa76555fb',
    messagingSenderId: '502778469026',
    projectId: 'lilac-flutter-machine-test',
    storageBucket: 'lilac-flutter-machine-test.appspot.com',
    iosClientId: '502778469026-e9cspvrodoojba6hod646f4akt96hgsq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lilacFlutterMachineTest',
  );
}
